### ISSUE TITLE
show error on invalid layer (eg. csv is empty)

### ISSUE THREAD

**Issue by landam** [ctu-fgis/2021-b-qgis-google-sheets-plugin#7]
https://docs.qgis.org/3.16/en/docs/pyqgis_developer_cookbook/communicating.html#showing-messages-the-qgsmessagebar-class

**Comment by Hoffmma5** [comment]
The error is handled together with issue n. 8. https://github.com/ctu-fgis/2021-b-qgis-google-sheets-plugin/issues/8

In a case of an invalid layer, which was in our testing always caused by putting invalid parameters to the X coord. column field or Y coord. column field, a pushMassage of "Invalid coordinate columns parameters" is shown on the screen.

https://github.com/ctu-fgis/2021-b-qgis-google-sheets-plugin/blob/master/google_sheets_downloader/google_sheets_downloader.py#:~:text=if%20not%20new_layer,level%3DQgis.Success)

If there was no such file called the way user put into the "Sheet name" field, a search() function in sp_gdrive.py resulted with an empty list and reaching of the list by indexing resulted in IndexError. The IndexError was solved by handling exceptions in the on_load() function. 

https://github.com/ctu-fgis/2021-b-qgis-google-sheets-plugin/blob/master/google_sheets_downloader/google_sheets_downloader.py#:~:text=try%3A,Ycol%2C%20self.CRS)
